name: codebook_app
description: A Flutter project for Codebook App.

publish_to: 'none' # Remove this if you want to publish

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  envied: ^0.3.0
  flutter_dotenv: ^5.0.2
  # Flutter & Dart packages
  provider: ^6.1.2
  firebase_core: ^2.27.0
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.17.4
  flutter_markdown: ^0.6.17
  lottie: ^2.7.0
  google_fonts: ^6.1.0
  permission_handler: ^11.3.1
  open_file: ^3.2.1
  intl: ^0.18.0
  reorderables: ^0.4.2
  flutter_highlight: ^0.7.0
  share_plus: ^7.2.1
  http: ^1.2.1
  pdf: ^3.10.4
  printing: ^5.12.0
  path_provider: ^2.0.11




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.7
  envied_generator: ^0.3.0
  flutter_launcher_icons: ^0.13.1
  


flutter:
  uses-material-design: true
  assets:
    - assets/images/codebook.png
    - assets/lottie/coding-bg.json
    - assets/fonts/RobotoMono-Regular.ttf
    - assets/fonts/OpenSans-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "./assets/icons/codebooks.png"