// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJhA-Q9nsdlFcM-1yXDY5HE-Zrfyv4o3w',
    appId: '1:719688679415:web:6c7f76c493cf806a68b8f2',
    messagingSenderId: '719688679415',
    projectId: 'codebook-app-ea943',
    authDomain: 'codebook-app-ea943.firebaseapp.com',
    storageBucket: 'codebook-app-ea943.firebasestorage.app',
    measurementId: 'G-RT579CS5GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7DjOIRSXzqKreAug6iAPcMJ5aTfToPXg',
    appId: '1:719688679415:android:637aa6786b95cf4f68b8f2',
    messagingSenderId: '719688679415',
    projectId: 'codebook-app-ea943',
    storageBucket: 'codebook-app-ea943.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4mCep7luRpi_3guOwqTyUaq2nH_zB7Fw',
    appId: '1:719688679415:ios:ebd6db6c9a4f359c68b8f2',
    messagingSenderId: '719688679415',
    projectId: 'codebook-app-ea943',
    storageBucket: 'codebook-app-ea943.firebasestorage.app',
    iosBundleId: 'com.example.codebookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4mCep7luRpi_3guOwqTyUaq2nH_zB7Fw',
    appId: '1:719688679415:ios:ebd6db6c9a4f359c68b8f2',
    messagingSenderId: '719688679415',
    projectId: 'codebook-app-ea943',
    storageBucket: 'codebook-app-ea943.firebasestorage.app',
    iosBundleId: 'com.example.codebookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJhA-Q9nsdlFcM-1yXDY5HE-Zrfyv4o3w',
    appId: '1:719688679415:web:1441cf718f3e6e2b68b8f2',
    messagingSenderId: '719688679415',
    projectId: 'codebook-app-ea943',
    authDomain: 'codebook-app-ea943.firebaseapp.com',
    storageBucket: 'codebook-app-ea943.firebasestorage.app',
    measurementId: 'G-QZV1E0YZC5',
  );
}
